GET http://localhost:3003/class/1/student

###
GET http://localhost:3003/class/1/teacher

###
GET http://localhost:3003/student/age/1

###
GET http://localhost:3003/student/hobby?description=correr

###
POST http://localhost:3003/student
Content-Type: application/json

{
    "name": "aluno1",
    "email": "aluno22@aluno.com",
    "birthDate": "01/08/2002",
    "hobbies": [{
        "description": "judo"
    },
    {
        "description": "natação"
    }]
}

###
POST http://localhost:3003/teacher
Content-Type: application/json

{
    "name": "professor",
    "email": "professor@professor.com",
    "birthDate": "20/05/1995",
    "specialties": [{
        "description": "CSS"
    }]
}

###
POST http://localhost:3003/class
Content-Type: application/json

{
    "name": "Nome_Turma",
    "startDate": "01/01/2021",
    "endDate": "06/06/2021",
    "module": 2,
    "period": "integral"
}

###
POST http://localhost:3003/class/student
Content-Type: application/json

{   
    "classId": 2,
    "studentId": 2
}

###
POST http://localhost:3003/class/teacher
Content-Type: application/json

{   
    "classId": 2,
    "teacherId": 2
}

###
PUT http://localhost:3003/class/1/module
Content-Type: application/json

{
    "module": 2
}

###
DELETE http://localhost:3003/class/2/student/1

###
DELETE http://localhost:3003/class/2/teacher/2